version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      FLASK_DEBUG: "1"
    volumes:
      - .:/app:ro
    user: "1000:1000"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tracetrack.tasks worker --loglevel=info
    depends_on:
      - redis
    user: "1000:1000"

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: flower -A tracetrack.tasks --port=5555
    depends_on:
      - redis    
    user: "1000:1000"

volumes:
  redis-data:

networks:
  default:
    name: tracetrack_network
